from selenium.webdriver.common.by import By

signup_popup_loc = (By.XPATH, "//span[contains(@class, 'icClose')]")
scan_to_download_app_popup_loc = (By.XPATH, "//div[@data-id='dweb_pip_id']//p")
iframe_push_prompt_loc = (By.ID, "webpush-onsite")
notifications_popup_loc = (By.XPATH, "//div/button[@id='deny']")
one_way_radio_loc = (By.XPATH, "//p[contains(text(), 'One')]//preceding-sibling::span")
round_trip_radio_loc = (By.XPATH, "//p[contains(text(), 'Round')]//preceding-sibling::span")
multi_city_radio_loc = (By.XPATH, "//p[contains(text(), 'Multi')]//preceding-sibling::span")
from_city_loc = (By.XPATH, "//span[contains(text(),'From')]//following-sibling::p[contains(text(), 'Enter city or airport')]")
dest_city_loc = (By.XPATH, "//span[contains(text(),'To')]//following-sibling::p[contains(text(), 'Enter city or airport')]")
from_city_loc_input = (By.XPATH, "//span[contains(text(),'From')]//following-sibling::input")
dest_city_loc_input = (By.XPATH, "//span[contains(text(),'To')]//following-sibling::input")
city_suggestion_list = (By.XPATH, "//ul[@id='autoSuggest-list']//p")
dept_date_loc = (By.XPATH, "//span[contains(text(), 'Departure')]//parent::div")
travellers_and_class_dropdown_button = (By.XPATH, "//p[contains(text(), 'Adult')]//span")
travellers_and_class_increase_count_of_Adults = (By.XPATH, "//p[contains(text(), 'Adults')]//parent::div//following::div/span[3]")
travellers_and_class_decrease_count_of_Adults = (By.XPATH, "//p[contains(text(), 'Adults')]//parent::div//following::div/span[1]")
travellers_and_class_increase_count_of_Children = (By.XPATH, "//p[contains(text(), 'Children')]//parent::div//following::div/span[3]")
travellers_and_class_decrease_count_of_Children = (By.XPATH, "//p[contains(text(), 'Children')]//parent::div//following::div/span[1]")
travellers_and_class_increase_count_of_Infants = (By.XPATH, "//p[contains(text(), 'Infants')]//parent::div//following::div/span[3]")
travellers_and_class_dcrease_count_of_Infants = (By.XPATH, "//p[contains(text(), 'Infants')]//parent::div//following::div/span[1]")
# travel_class_loc = (By.XPATH, "//p[contains(text(), 'Travel Class')]//parent::div//ul")
travellers_and_class_submit_loc = (By.XPATH, "//p[contains(text(), 'Travel Class')]//parent::div//following::div/a[text()='Done']")
special_fares_for_student = (By.XPATH, "//input[@id='ST']//parent::div")
special_student_radio = (By.XPATH, "//input[@id='ST']")
search_flights_button_loc = (By.XPATH, "//span[contains(text(), 'SEARCH FLIGHTS')]")